//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УМК_Цифра.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> ScorePoint { get; set; }
        public string Gihub { get; set; }
        public Nullable<int> ScoreOtrasl { get; set; }
        public Nullable<int> ScoreSIZ { get; set; }
        public Nullable<int> ScoreZone { get; set; }
        public Nullable<int> ScoreShablon { get; set; }
        public Nullable<int> ScoreRazmer { get; set; }
        public Nullable<int> ScoreZvet { get; set; }
        public Nullable<int> ScoreKachestvo { get; set; }
        public Nullable<int> ScoreKod { get; set; }
    }
}
